name: Build and Deploy Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # You can adjust this to your specific Go version

    - name: Build
      run: |
        cd backend  # Adjust this path to where your Go code is
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cardsorter ./cmd/main.go  # Adjust the path to your main.go

    - name: Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa
        
        # Create target directory and copy binary
        ssh kit@klaital.com 'mkdir -p /home/kit/bin/cardsorter'
        scp backend/cardsorter kit@klaital.com:/home/kit/bin/cardsorter/cardsorter_new