# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import cards_pb2 as cards__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCard = channel.unary_unary(
                '/card.v1.CardService/CreateCard',
                request_serializer=cards__pb2.CreateCardRequest.SerializeToString,
                response_deserializer=cards__pb2.CreateCardResponse.FromString,
                _registered_method=True)
        self.GetCards = channel.unary_unary(
                '/card.v1.CardService/GetCards',
                request_serializer=cards__pb2.GetCardsRequest.SerializeToString,
                response_deserializer=cards__pb2.GetCardsResponse.FromString,
                _registered_method=True)
        self.GetCard = channel.unary_unary(
                '/card.v1.CardService/GetCard',
                request_serializer=cards__pb2.GetCardRequest.SerializeToString,
                response_deserializer=cards__pb2.GetCardResponse.FromString,
                _registered_method=True)
        self.MoveCard = channel.unary_unary(
                '/card.v1.CardService/MoveCard',
                request_serializer=cards__pb2.MoveCardRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteCard = channel.unary_unary(
                '/card.v1.CardService/DeleteCard',
                request_serializer=cards__pb2.DeleteCardRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCard(self, request, context):
        """CreateCard creates a new card in a library
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCards(self, request, context):
        """GetCards retrieves all cards in a library
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCard(self, request, context):
        """GetCard retrieves a specific card
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveCard(self, request, context):
        """MoveCard moves a card to a different library
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCard(self, request, context):
        """DeleteCard removes a card from a library
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCard': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCard,
                    request_deserializer=cards__pb2.CreateCardRequest.FromString,
                    response_serializer=cards__pb2.CreateCardResponse.SerializeToString,
            ),
            'GetCards': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCards,
                    request_deserializer=cards__pb2.GetCardsRequest.FromString,
                    response_serializer=cards__pb2.GetCardsResponse.SerializeToString,
            ),
            'GetCard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCard,
                    request_deserializer=cards__pb2.GetCardRequest.FromString,
                    response_serializer=cards__pb2.GetCardResponse.SerializeToString,
            ),
            'MoveCard': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveCard,
                    request_deserializer=cards__pb2.MoveCardRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteCard': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCard,
                    request_deserializer=cards__pb2.DeleteCardRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'card.v1.CardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('card.v1.CardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/card.v1.CardService/CreateCard',
            cards__pb2.CreateCardRequest.SerializeToString,
            cards__pb2.CreateCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/card.v1.CardService/GetCards',
            cards__pb2.GetCardsRequest.SerializeToString,
            cards__pb2.GetCardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/card.v1.CardService/GetCard',
            cards__pb2.GetCardRequest.SerializeToString,
            cards__pb2.GetCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/card.v1.CardService/MoveCard',
            cards__pb2.MoveCardRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/card.v1.CardService/DeleteCard',
            cards__pb2.DeleteCardRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
