# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x07user.v1\x1a\x1cgoogle/api/annotations.proto\"E\n\x11\x43reateUserRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\":\n\x12\x43reateUserResponse\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n\x05token\x18\x02 \x01(\tR\x05token\"@\n\x0cLoginRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\">\n\rLoginResponse\x12\x17\n\x07user_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n\x05token\x18\x02 \x01(\tR\x05token2\xb8\x01\n\x0bUserService\x12[\n\nCreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x1b.user.v1.CreateUserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\"\t/v1/users:\x01*\x12L\n\x05Login\x12\x15.user.v1.LoginRequest\x1a\x16.user.v1.LoginResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\"\t/v1/login:\x01*B9Z7github.com/klaital/cardsorter/backend/gen/protos;cardv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/klaital/cardsorter/backend/gen/protos;cardv1'
  _globals['_USERSERVICE'].methods_by_name['CreateUser']._loaded_options = None
  _globals['_USERSERVICE'].methods_by_name['CreateUser']._serialized_options = b'\202\323\344\223\002\016\"\t/v1/users:\001*'
  _globals['_USERSERVICE'].methods_by_name['Login']._loaded_options = None
  _globals['_USERSERVICE'].methods_by_name['Login']._serialized_options = b'\202\323\344\223\002\016\"\t/v1/login:\001*'
  _globals['_CREATEUSERREQUEST']._serialized_start=53
  _globals['_CREATEUSERREQUEST']._serialized_end=122
  _globals['_CREATEUSERRESPONSE']._serialized_start=124
  _globals['_CREATEUSERRESPONSE']._serialized_end=182
  _globals['_LOGINREQUEST']._serialized_start=184
  _globals['_LOGINREQUEST']._serialized_end=248
  _globals['_LOGINRESPONSE']._serialized_start=250
  _globals['_LOGINRESPONSE']._serialized_end=312
  _globals['_USERSERVICE']._serialized_start=315
  _globals['_USERSERVICE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
