// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Card struct {
	ID           int64        `json:"id"`
	LibraryID    int64        `json:"library_id"`
	Name         string       `json:"name"`
	SetName      string       `json:"set_name"`
	CollectorNum string       `json:"collector_num"`
	Cnd          string       `json:"cnd"`
	Foil         sql.NullBool `json:"foil"`
	Usd          int32        `json:"usd"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type Library struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
