// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createCard = `-- name: CreateCard :execresult
INSERT INTO cards (library_id, name, set_name, cnd, foil, collector_num, usd, qty, scryfall_card_id)
VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?)
ON DUPLICATE KEY UPDATE
    qty = qty + 1
`

type CreateCardParams struct {
	LibraryID      int64         `json:"library_id"`
	Name           string        `json:"name"`
	SetName        string        `json:"set_name"`
	Cnd            string        `json:"cnd"`
	Foil           sql.NullBool  `json:"foil"`
	CollectorNum   string        `json:"collector_num"`
	Usd            int32         `json:"usd"`
	ScryfallCardID sql.NullInt64 `json:"scryfall_card_id"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (sql.Result, error) {
	return q.exec(ctx, q.createCardStmt, createCard,
		arg.LibraryID,
		arg.Name,
		arg.SetName,
		arg.Cnd,
		arg.Foil,
		arg.CollectorNum,
		arg.Usd,
		arg.ScryfallCardID,
	)
}

const createLibrary = `-- name: CreateLibrary :execresult
INSERT INTO libraries (user_id, name)
VALUES (?, ?)
`

type CreateLibraryParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (sql.Result, error) {
	return q.exec(ctx, q.createLibraryStmt, createLibrary, arg.UserID, arg.Name)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (email, password_hash)
VALUES (?, ?)
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.exec(ctx, q.createUserStmt, createUser, arg.Email, arg.PasswordHash)
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards
WHERE id = ?
`

func (q *Queries) DeleteCard(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteCardStmt, deleteCard, id)
	return err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM libraries
WHERE id = ? AND user_id = ? LIMIT 1
`

type DeleteLibraryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteLibrary(ctx context.Context, arg DeleteLibraryParams) error {
	_, err := q.exec(ctx, q.deleteLibraryStmt, deleteLibrary, arg.ID, arg.UserID)
	return err
}

const getCard = `-- name: GetCard :one
SELECT
    c.id, c.library_id, c.name, c.set_name, c.collector_num, c.cnd, c.foil, c.usd, c.created_at, c.updated_at, c.qty, c.scryfall_card_id,
    ac.name as scryfall_name,
    ac.rarity,
    CASE
        WHEN c.foil = TRUE THEN cp.usd_foil
        ELSE cp.usd
    END as current_usd_price
FROM cards c
LEFT JOIN all_cards ac ON c.scryfall_card_id = ac.id
LEFT JOIN card_prices cp ON ac.id = cp.card_id
WHERE c.id = ?
`

type GetCardRow struct {
	ID              int64          `json:"id"`
	LibraryID       int64          `json:"library_id"`
	Name            string         `json:"name"`
	SetName         string         `json:"set_name"`
	CollectorNum    string         `json:"collector_num"`
	Cnd             string         `json:"cnd"`
	Foil            sql.NullBool   `json:"foil"`
	Usd             int32          `json:"usd"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	Qty             uint32         `json:"qty"`
	ScryfallCardID  sql.NullInt64  `json:"scryfall_card_id"`
	ScryfallName    sql.NullString `json:"scryfall_name"`
	Rarity          sql.NullString `json:"rarity"`
	CurrentUsdPrice interface{}    `json:"current_usd_price"`
}

func (q *Queries) GetCard(ctx context.Context, id int64) (GetCardRow, error) {
	row := q.queryRow(ctx, q.getCardStmt, getCard, id)
	var i GetCardRow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.SetName,
		&i.CollectorNum,
		&i.Cnd,
		&i.Foil,
		&i.Usd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Qty,
		&i.ScryfallCardID,
		&i.ScryfallName,
		&i.Rarity,
		&i.CurrentUsdPrice,
	)
	return i, err
}

const getCards = `-- name: GetCards :many
SELECT
    c.id, c.library_id, c.name, c.set_name, c.collector_num, c.cnd, c.foil, c.usd, c.created_at, c.updated_at, c.qty, c.scryfall_card_id,
    ac.name as scryfall_name,
    ac.rarity,
    CASE
        WHEN c.foil = TRUE THEN cp.usd_foil
        ELSE cp.usd
    END as current_usd_price
FROM cards c
LEFT JOIN all_cards ac ON c.scryfall_card_id = ac.id
LEFT JOIN card_prices cp ON ac.id = cp.card_id
WHERE c.library_id = ?
`

type GetCardsRow struct {
	ID              int64          `json:"id"`
	LibraryID       int64          `json:"library_id"`
	Name            string         `json:"name"`
	SetName         string         `json:"set_name"`
	CollectorNum    string         `json:"collector_num"`
	Cnd             string         `json:"cnd"`
	Foil            sql.NullBool   `json:"foil"`
	Usd             int32          `json:"usd"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	Qty             uint32         `json:"qty"`
	ScryfallCardID  sql.NullInt64  `json:"scryfall_card_id"`
	ScryfallName    sql.NullString `json:"scryfall_name"`
	Rarity          sql.NullString `json:"rarity"`
	CurrentUsdPrice interface{}    `json:"current_usd_price"`
}

func (q *Queries) GetCards(ctx context.Context, libraryID int64) ([]GetCardsRow, error) {
	rows, err := q.query(ctx, q.getCardsStmt, getCards, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCardsRow
	for rows.Next() {
		var i GetCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.SetName,
			&i.CollectorNum,
			&i.Cnd,
			&i.Foil,
			&i.Usd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Qty,
			&i.ScryfallCardID,
			&i.ScryfallName,
			&i.Rarity,
			&i.CurrentUsdPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLibraries = `-- name: GetLibraries :many
SELECT
    l.id,
    l.name,
    COALESCE(SUM(
        CASE
            WHEN c.foil = TRUE THEN COALESCE(cp.usd_foil, c.usd)
            ELSE COALESCE(cp.usd, c.usd)
        END * c.qty
    ), 0) as total_value
FROM
    libraries l
        LEFT JOIN cards c ON l.id = c.library_id
        LEFT JOIN all_cards ac ON c.scryfall_card_id = ac.id
        LEFT JOIN card_prices cp ON ac.id = cp.card_id
WHERE l.user_id = ?
GROUP BY
    l.id, l.name
ORDER BY
    l.id
`

type GetLibrariesRow struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	TotalValue interface{} `json:"total_value"`
}

func (q *Queries) GetLibraries(ctx context.Context, userID int64) ([]GetLibrariesRow, error) {
	rows, err := q.query(ctx, q.getLibrariesStmt, getLibraries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLibrariesRow
	for rows.Next() {
		var i GetLibrariesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TotalValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, user_id, name, created_at, updated_at FROM libraries
WHERE id = ? AND user_id = ?
`

type GetLibraryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetLibrary(ctx context.Context, arg GetLibraryParams) (Library, error) {
	row := q.queryRow(ctx, q.getLibraryStmt, getLibrary, arg.ID, arg.UserID)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCardCount = `-- name: IncrementCardCount :exec
UPDATE cards
SET qty = qty + 1
WHERE id = ?
`

func (q *Queries) IncrementCardCount(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.incrementCardCountStmt, incrementCardCount, id)
	return err
}

const moveCard = `-- name: MoveCard :exec
UPDATE cards
SET library_id = ?
WHERE id = ?
`

type MoveCardParams struct {
	LibraryID int64 `json:"library_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) MoveCard(ctx context.Context, arg MoveCardParams) error {
	_, err := q.exec(ctx, q.moveCardStmt, moveCard, arg.LibraryID, arg.ID)
	return err
}

const updateCard = `-- name: UpdateCard :exec
UPDATE cards
SET name=?, usd=?
WHERE id=?
`

type UpdateCardParams struct {
	Name string `json:"name"`
	Usd  int32  `json:"usd"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.exec(ctx, q.updateCardStmt, updateCard, arg.Name, arg.Usd, arg.ID)
	return err
}
