// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCard(ctx context.Context, arg CreateCardParams) (sql.Result, error)
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteCard(ctx context.Context, id int64) error
	DeleteLibrary(ctx context.Context, arg DeleteLibraryParams) error
	GetCard(ctx context.Context, id int64) (Card, error)
	GetCards(ctx context.Context, libraryID int64) ([]Card, error)
	GetLibraries(ctx context.Context, userID int64) ([]GetLibrariesRow, error)
	GetLibrary(ctx context.Context, arg GetLibraryParams) (Library, error)
	GetUser(ctx context.Context, email string) (User, error)
	MoveCard(ctx context.Context, arg MoveCardParams) error
}

var _ Querier = (*Queries)(nil)
