// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scryfall.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const completeScryfallProcessing = `-- name: CompleteScryfallProcessing :exec
UPDATE scryfall_bulk
SET processing_completed_at = NOW()
WHERE id = ?
`

func (q *Queries) CompleteScryfallProcessing(ctx context.Context, id uint32) error {
	_, err := q.exec(ctx, q.completeScryfallProcessingStmt, completeScryfallProcessing, id)
	return err
}

const getScryfallBulkBySID = `-- name: GetScryfallBulkBySID :one
SELECT id, scryfall_id, scryfall_type, updated_at, uri, size, download_uri, processing_started_at, processing_completed_at FROM scryfall_bulk WHERE scryfall_id = UUID_TO_BIN(?)
`

func (q *Queries) GetScryfallBulkBySID(ctx context.Context, uuidTOBIN string) (ScryfallBulk, error) {
	row := q.queryRow(ctx, q.getScryfallBulkBySIDStmt, getScryfallBulkBySID, uuidTOBIN)
	var i ScryfallBulk
	err := row.Scan(
		&i.ID,
		&i.ScryfallID,
		&i.ScryfallType,
		&i.UpdatedAt,
		&i.Uri,
		&i.Size,
		&i.DownloadUri,
		&i.ProcessingStartedAt,
		&i.ProcessingCompletedAt,
	)
	return i, err
}

const getScryfallBulkByType = `-- name: GetScryfallBulkByType :many
SELECT id, scryfall_id, scryfall_type, updated_at, uri, size, download_uri, processing_started_at, processing_completed_at FROM scryfall_bulk WHERE scryfall_type = ?
`

func (q *Queries) GetScryfallBulkByType(ctx context.Context, scryfallType string) ([]ScryfallBulk, error) {
	rows, err := q.query(ctx, q.getScryfallBulkByTypeStmt, getScryfallBulkByType, scryfallType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScryfallBulk
	for rows.Next() {
		var i ScryfallBulk
		if err := rows.Scan(
			&i.ID,
			&i.ScryfallID,
			&i.ScryfallType,
			&i.UpdatedAt,
			&i.Uri,
			&i.Size,
			&i.DownloadUri,
			&i.ProcessingStartedAt,
			&i.ProcessingCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScryfallCardBySID = `-- name: GetScryfallCardBySID :one
SELECT id, scryfall_id, lang, layout, set_name, digital, rarity, name, collector_number FROM all_cards WHERE scryfall_id = UUID_TO_BIN(?)
`

func (q *Queries) GetScryfallCardBySID(ctx context.Context, uuidTOBIN string) (AllCard, error) {
	row := q.queryRow(ctx, q.getScryfallCardBySIDStmt, getScryfallCardBySID, uuidTOBIN)
	var i AllCard
	err := row.Scan(
		&i.ID,
		&i.ScryfallID,
		&i.Lang,
		&i.Layout,
		&i.SetName,
		&i.Digital,
		&i.Rarity,
		&i.Name,
		&i.CollectorNumber,
	)
	return i, err
}

const getScryfallCardBySetAndNumber = `-- name: GetScryfallCardBySetAndNumber :one
SELECT id, scryfall_id, lang, layout, set_name, digital, rarity, name, collector_number FROM all_cards WHERE set_name = ? AND collector_number = ? LIMIT 1
`

type GetScryfallCardBySetAndNumberParams struct {
	SetName         string `json:"set_name"`
	CollectorNumber string `json:"collector_number"`
}

func (q *Queries) GetScryfallCardBySetAndNumber(ctx context.Context, arg GetScryfallCardBySetAndNumberParams) (AllCard, error) {
	row := q.queryRow(ctx, q.getScryfallCardBySetAndNumberStmt, getScryfallCardBySetAndNumber, arg.SetName, arg.CollectorNumber)
	var i AllCard
	err := row.Scan(
		&i.ID,
		&i.ScryfallID,
		&i.Lang,
		&i.Layout,
		&i.SetName,
		&i.Digital,
		&i.Rarity,
		&i.Name,
		&i.CollectorNumber,
	)
	return i, err
}

const getScryfallCardByValue = `-- name: GetScryfallCardByValue :one
SELECT all_cards.id, all_cards.scryfall_id, all_cards.lang, all_cards.layout, all_cards.set_name, all_cards.digital, all_cards.rarity, all_cards.name, all_cards.collector_number,
       card_prices.usd, card_prices.usd_foil,
       card_prices.usd_etched, card_prices.eur,
       card_prices.eur_foil, card_prices.tix
FROM all_cards
    LEFT OUTER JOIN card_prices
    ON all_cards.id = card_prices.card_id
`

type GetScryfallCardByValueRow struct {
	ID              uint64        `json:"id"`
	ScryfallID      []byte        `json:"scryfall_id"`
	Lang            string        `json:"lang"`
	Layout          string        `json:"layout"`
	SetName         string        `json:"set_name"`
	Digital         bool          `json:"digital"`
	Rarity          string        `json:"rarity"`
	Name            string        `json:"name"`
	CollectorNumber string        `json:"collector_number"`
	Usd             sql.NullInt32 `json:"usd"`
	UsdFoil         sql.NullInt32 `json:"usd_foil"`
	UsdEtched       sql.NullInt32 `json:"usd_etched"`
	Eur             sql.NullInt32 `json:"eur"`
	EurFoil         sql.NullInt32 `json:"eur_foil"`
	Tix             sql.NullInt32 `json:"tix"`
}

func (q *Queries) GetScryfallCardByValue(ctx context.Context) (GetScryfallCardByValueRow, error) {
	row := q.queryRow(ctx, q.getScryfallCardByValueStmt, getScryfallCardByValue)
	var i GetScryfallCardByValueRow
	err := row.Scan(
		&i.ID,
		&i.ScryfallID,
		&i.Lang,
		&i.Layout,
		&i.SetName,
		&i.Digital,
		&i.Rarity,
		&i.Name,
		&i.CollectorNumber,
		&i.Usd,
		&i.UsdFoil,
		&i.UsdEtched,
		&i.Eur,
		&i.EurFoil,
		&i.Tix,
	)
	return i, err
}

const insertScryfallBulk = `-- name: InsertScryfallBulk :execresult
INSERT INTO scryfall_bulk (scryfall_id, scryfall_type, updated_at, uri, size, download_uri)
VALUES (UUID_TO_BIN(?), ?, ?, ?, ?, ?)
`

type InsertScryfallBulkParams struct {
	UUIDTOBIN    string    `json:"UUID_TO_BIN"`
	ScryfallType string    `json:"scryfall_type"`
	UpdatedAt    time.Time `json:"updated_at"`
	Uri          string    `json:"uri"`
	Size         int32     `json:"size"`
	DownloadUri  string    `json:"download_uri"`
}

func (q *Queries) InsertScryfallBulk(ctx context.Context, arg InsertScryfallBulkParams) (sql.Result, error) {
	return q.exec(ctx, q.insertScryfallBulkStmt, insertScryfallBulk,
		arg.UUIDTOBIN,
		arg.ScryfallType,
		arg.UpdatedAt,
		arg.Uri,
		arg.Size,
		arg.DownloadUri,
	)
}

const insertScryfallCard = `-- name: InsertScryfallCard :execresult
INSERT INTO all_cards (scryfall_id, lang, layout, set_name, digital, rarity, name, collector_number)
VALUES (UUID_TO_BIN(?), ?, ?, ?, ?, ?, ?, ?)
`

type InsertScryfallCardParams struct {
	UUIDTOBIN       string `json:"UUID_TO_BIN"`
	Lang            string `json:"lang"`
	Layout          string `json:"layout"`
	SetName         string `json:"set_name"`
	Digital         bool   `json:"digital"`
	Rarity          string `json:"rarity"`
	Name            string `json:"name"`
	CollectorNumber string `json:"collector_number"`
}

func (q *Queries) InsertScryfallCard(ctx context.Context, arg InsertScryfallCardParams) (sql.Result, error) {
	return q.exec(ctx, q.insertScryfallCardStmt, insertScryfallCard,
		arg.UUIDTOBIN,
		arg.Lang,
		arg.Layout,
		arg.SetName,
		arg.Digital,
		arg.Rarity,
		arg.Name,
		arg.CollectorNumber,
	)
}

const insertScryfallFace = `-- name: InsertScryfallFace :exec
INSERT INTO card_faces (card_id, flavor_text, layout, name, original_image_uri_png, original_image_uri_large, original_image_uri_small)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertScryfallFaceParams struct {
	CardID                uint64         `json:"card_id"`
	FlavorText            sql.NullString `json:"flavor_text"`
	Layout                sql.NullString `json:"layout"`
	Name                  string         `json:"name"`
	OriginalImageUriPng   sql.NullString `json:"original_image_uri_png"`
	OriginalImageUriLarge sql.NullString `json:"original_image_uri_large"`
	OriginalImageUriSmall sql.NullString `json:"original_image_uri_small"`
}

func (q *Queries) InsertScryfallFace(ctx context.Context, arg InsertScryfallFaceParams) error {
	_, err := q.exec(ctx, q.insertScryfallFaceStmt, insertScryfallFace,
		arg.CardID,
		arg.FlavorText,
		arg.Layout,
		arg.Name,
		arg.OriginalImageUriPng,
		arg.OriginalImageUriLarge,
		arg.OriginalImageUriSmall,
	)
	return err
}

const listScryfallBulks = `-- name: ListScryfallBulks :many
SELECT id, scryfall_id, scryfall_type, updated_at, uri, size, download_uri, processing_started_at, processing_completed_at FROM scryfall_bulk
`

func (q *Queries) ListScryfallBulks(ctx context.Context) ([]ScryfallBulk, error) {
	rows, err := q.query(ctx, q.listScryfallBulksStmt, listScryfallBulks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScryfallBulk
	for rows.Next() {
		var i ScryfallBulk
		if err := rows.Scan(
			&i.ID,
			&i.ScryfallID,
			&i.ScryfallType,
			&i.UpdatedAt,
			&i.Uri,
			&i.Size,
			&i.DownloadUri,
			&i.ProcessingStartedAt,
			&i.ProcessingCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setScryfallPrices = `-- name: SetScryfallPrices :exec
INSERT INTO card_prices (card_id, usd, usd_foil, usd_etched, eur, eur_foil, tix)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    usd = ?, usd_foil = ?, usd_etched = ?,
    eur = ?, eur_foil = ?,
    tix = ?
`

type SetScryfallPricesParams struct {
	CardID      uint64        `json:"card_id"`
	Usd         sql.NullInt32 `json:"usd"`
	UsdFoil     sql.NullInt32 `json:"usd_foil"`
	UsdEtched   sql.NullInt32 `json:"usd_etched"`
	Eur         sql.NullInt32 `json:"eur"`
	EurFoil     sql.NullInt32 `json:"eur_foil"`
	Tix         sql.NullInt32 `json:"tix"`
	Usd_2       sql.NullInt32 `json:"usd_2"`
	UsdFoil_2   sql.NullInt32 `json:"usd_foil_2"`
	UsdEtched_2 sql.NullInt32 `json:"usd_etched_2"`
	Eur_2       sql.NullInt32 `json:"eur_2"`
	EurFoil_2   sql.NullInt32 `json:"eur_foil_2"`
	Tix_2       sql.NullInt32 `json:"tix_2"`
}

func (q *Queries) SetScryfallPrices(ctx context.Context, arg SetScryfallPricesParams) error {
	_, err := q.exec(ctx, q.setScryfallPricesStmt, setScryfallPrices,
		arg.CardID,
		arg.Usd,
		arg.UsdFoil,
		arg.UsdEtched,
		arg.Eur,
		arg.EurFoil,
		arg.Tix,
		arg.Usd_2,
		arg.UsdFoil_2,
		arg.UsdEtched_2,
		arg.Eur_2,
		arg.EurFoil_2,
		arg.Tix_2,
	)
	return err
}

const startScryfallProcessing = `-- name: StartScryfallProcessing :exec
UPDATE scryfall_bulk
SET processing_started_at = NOW()
WHERE id = ?
`

func (q *Queries) StartScryfallProcessing(ctx context.Context, id uint32) error {
	_, err := q.exec(ctx, q.startScryfallProcessingStmt, startScryfallProcessing, id)
	return err
}

const updateCardCollectorNumber = `-- name: UpdateCardCollectorNumber :exec
UPDATE all_cards SET collector_number = ? WHERE scryfall_id = UUID_TO_BIN(?)
`

type UpdateCardCollectorNumberParams struct {
	CollectorNumber string `json:"collector_number"`
	UUIDTOBIN       string `json:"UUID_TO_BIN"`
}

func (q *Queries) UpdateCardCollectorNumber(ctx context.Context, arg UpdateCardCollectorNumberParams) error {
	_, err := q.exec(ctx, q.updateCardCollectorNumberStmt, updateCardCollectorNumber, arg.CollectorNumber, arg.UUIDTOBIN)
	return err
}
