name: Build Backend

on:
  push:
    branches:
      - '**'  # Matches all branches
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        cd backend
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cardsorter ./cmd/main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cardsorter-binary
        path: backend/cardsorter
        retention-days: 5